TL/urls.py
from django.contrib import admin
from django.urls import path,include
from articles.views import articles_list

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/' , include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('', articles_list),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from. import views

app_name="accounts"
urlpatterns = [
path('signin' , views.signin , name="signin"),
path('signup' , views.signup , name="signup"),
path('signout' , views.signout , name="signout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name= "articles"
urlpatterns = [
    path('', views.articles_list, name="list"),
    path('creat',views.creat_article,name="creat"),
    path('<slug>',views.details,name="details"),

]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    image = models.ImageField(default='default.jpg',blank=True )
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from . import models
from django import forms


class CreatArticle (forms.ModelForm):
    class Meta:
        model=models.Article
        fields=['title','slug','body','image']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.http import HttpResponse

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def signin(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)

            return redirect('articles:list')
    else:
        form=AuthenticationForm()
        return render(request,'accounts/signin.html',{'form':form})


def signout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')
    else :
        return render (request ,'accounts/signout.html')

articles/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.http import HttpResponse
from . import models,forms

# Create your views here.



def articles_list(request):
    articles1 = models.Article.objects.all()
    arg={'articles':articles1}
    return render(request, 'articles/articles_list.html',arg)

def creat_article(request):
    if request.method=='POST':
        form=forms.CreatArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
        return redirect('articles:list')

    else :
        form=forms.CreatArticle()
    return render (request,'articles/creat_article.html',{'form':form})


#    return render(request,'articles/creat_article.html')


def details(request,slug):
    article=models.Article.objects.get (slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

accounts/templates/accounts/signin.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="site-form" action="{% url 'accounts:signin' %}" method="post">
  {{form}}
  {% csrf_token %}
  {% if request.GET.next %}
  <input type="hidden" name="next" value="{{request.GET.next}}">
  {% endif %}
  <input type="submit" value="login">
</form>
  </body>
</html>

accounts/templates/accounts/signout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="logout-link" action="{% url 'accounts:signout' %}" method="post">
  {% csrf_token %}
  <button type="submit">logout</button>
</form>
  </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {{form}}
  {% csrf_token %}
  <input type="submit" value="signup">
</form>
  </body>
</html>

articles/templates/articles/article_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
      <P> kirrrrrrrrrrrrrrrrrrrrrrrrrr </p>

  </body>
</html>

articles/templates/articles/articles_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% for article in articles %}
    <h1>title.article</h1>
    <h2>body.article</h2>
    <h3>slug.article</h3>
    {% endfor %}
  </body>
</html>

articles/templates/articles/creat_article.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>mikhorish</title>
  </head>
  <body>
    <div class="create-article">
      <h1>
        create your article!
      </h1>
      <form class="site-form" action="{% url 'articles:creat' %}" method="post" enctype="multipart/form-data">
        {{form}}
        {% csrf_token %}
        <input type="submit" name="" value="create">
      </form>
    </div>
  </body>
</html>